CURSOS = {
    "Engenharia Civil": {
        "Ementa - 2011": {
            "1º Semestre": [
                "Cálculo Diferencial e Integral I – CM201",
                "Eletricidade Aplicada – TE144",
                "Expressão Gráfica I – CD027",
                "Geometria Analítica – CM045",
                "Introdução à Engenharia – TC022",
                "Mecânica Geral I – TC021",
                "Programação de Computadores – CI208"
            ],
            "2º Semestre": [
                "Álgebra Linear – CM005",
                "Cálculo Diferencial e Integral II – CM202",
                "Construção Civil I – TC024",
                "Expressão Gráfica II – CD028",
                "Mecânica Geral II – TC023",
                "Métodos Numéricos – CI202"
            ],
            "3º Semestre": [
                "Cálculo III – CM043",
                "Construção Civil II – TC025",
                "Estatística II – CE003",
                "Mecânica dos Fluidos I – TH019",
                "Mecânica Geral III – TC027",
                "Resistência dos Materiais I – TC026",
                "Topografia I – GA069"
            ],
            "4º Semestre": [
                "Introdução à Engenharia Geotécnica – TC029",
                "Ciências do Ambiente – TH022",
                "Materiais de Construção Civil I – TC030",
                "Mecânica dos Fluidos II – TH021",
                "Resistência dos Materiais II – TC028",
                "Sistemas de Transporte – TT046",
                "Topografia II – GA070"
            ],
            "5º Semestre": [
                "Estruturação Sanitária das Cidades – TH025",
                "Hidráulica – TH020",
                "Infra-Estrutura Viária – TT048",
                "Laboratório de Mecânica dos Solos – TC033",
                "Materiais de Construção Civil II – TC031",
                "Mecânica das Estruturas I – TC032"
            ],
            "6º Semestre": [
                "Atividades Formativas – AAC005",
                "Equipamentos de Construção e Conservação – TT047",
                "Hidráulica e Hidrologia Experimental – TH027",
                "Hidrologia – TH024",
                "Materiais de Construção Civil III – TC034",
                "Mecânica das Estruturas II – TC036",
                "Mecânica dos Solos – TC035"
            ],
            "7º Semestre": [
                "Construção Civil III – TC038",
                "Engenharia de Recursos Hídricos – TH026",
                "Engenharia Social – TH045",
                "Estruturas de Concreto I – TC037",
                "Laboratório de Materiais de Construção – TC039",
                "Obras Geotécnicas – TC066",
                "Planejamento de Transportes – TT049",
                "Saneamento Ambiental I – TH028"
            ],
            "8º Semestre": [
                "Construção Civil IV – TC042",
                "Economia de Engenharia I – TT007",
                "Estágio Supervisionado – TC046",
                "Estágio Supervisionado – TH043",
                "Estágio Supervisionado – TT054",
                "Estruturas de Concreto II – TC040",
                "Geotecnia de Fundações – TC041",
                "Pavimentação – TT051",
                "Saneamento Ambiental II – TH029"
            ],
            "9º Semestre": [
                "Administração de Empresas de Engenharia I – TT008",
                "Estrutura de Edifícios I – TC044",
                "Estruturas Metálicas I – TC043",
                "Gerenciamento de Projetos – TC045",
                "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
                "Trabalho Final de Curso I – TC081",
                "Trabalho Final de Curso I – TH061",
                "Trabalho Final de Curso I – TT071"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC082",
                "Trabalho Final de Curso II – TH062",
                "Trabalho Final de Curso II – TT072"
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        },
        "Ementa - 2023": {
            "1º Semestre": [
                "Expressão Gráfica A – CEG019",
                "Fundamentação de Programação de Computadores – CI182",
                "Pré-Cálculo – CM310",
                "Física I – TC501",
                "Química Aplicada – TC502",
                "Introdução à Engenharia e Inovação – TC591",
                "Introdução à Engenharia e Inovação – TH591",
                "Introdução à Engenharia e Inovação – TT591"
            ],
            "2º Semestre": [
                "Métodos Numéricos – CI202",
                "Introdução à Geometria Analítica e Álgebra Linear – CM303",
                "Cálculo 1 – CM311",
                "Desenho Arquitetônico – TC503",
                "Análise Estrutural I – TC504",
                "Física II – TH512"
            ],
            "3º Semestre": [
                "Introdução à Estatística – CE009",
                "Cálculo 2 – CM312",
                "Topografia I – GA175",
                "Construção Civil I – TC505",
                "Análise Estrutural II – TC506",
                "Sistemas Estruturais – TC507",
                "Mecânica dos Fluídos I – TH501",
                "Sistemas de Transporte – TT501"
            ],
            "4º Semestre": [
                "Cálculo 4 – CM314",
                "Topografia II – GA176",
                "Construção Civil II – TC508",
                "Mecânica dos Sólidos I – TC509",
                "Materiais de Construção Civil I – TC510",
                "Laboratório de Materiais de Construção Civil – TC511",
                "Mecânica dos Fluídos II – TH502",
                "Mecânica dos Fluídos Experimental – TH503"
            ],
            "5º Semestre": [
                "Caracterização Geológica - Geotécnica – TC512",
                "Mecânica dos Sólidos II – TC513",
                "Materiais de Construção Civil II – TC514",
                "Hidráulica – TH504",
                "Ciências do Ambiente – TH508",
                "Planejamento e Operação de Transportes – TT502",
                "Engenharia Civil e Sustentabilidade – TC592",
                "Engenharia Civil e Sustentabilidade – TH592",
                "Engenharia Civil e Sustentabilidade – TT592",
            ],
            "6º Semestre": [
                "Hidráulica dos Solos – TC515",
                "Análise Estrutural III – TC516",
                "Construção Civil III – TC517",
                "Hidrologia – TH505",
                "Hidráulica e Hidrologia Experimental – TH506",
                "Equipamentos de Terraplanagem e de Pavimentação – TT503",
                "Estruturação das Cidades – TH593",
                "Estruturação das Cidades – TT593"
            ],
            "7º Semestre": [
                "Mecânica dos Solos – TC518",
                "Estruturas de Concreto I – TC519",
                "Gestão de Projetos – TC520",
                "Engenharia de Recursos Hídricos – TH507",
                "Saneamento Ambiental I – TH509",
                "Engenharia Econômica – TT504",
                "Engenharia Urbana – TH594",
                "Engenharia Urbana – TT594"
            ],
            "8º Semestre": [
                "Obras Geotécnicas – TC521",
                "Estruturas de Concreto II – TC522",
                "Saneamento Ambiental II – TH510",
                "Estradas – TT505",
                "Pavimentação – TT506",
                "Laboratório de Transportes – TT507",
                "Economia de Engenharia – TT508",
                "Metodologia do Trabalho Científico e Tecnológico – TT509"
            ],
            "9º Semestre": [
                "Estruturas de Aço – TC523",
                "Estruturas de Madeira – TC524",
                "Engenharia de Fundações – TC525",
                "Eletricidade Aplicada – TE144",
                "Engenharia e Sociedade – TH511",
                "Administração de Empresas – TT510",
                "Trabalho Final de Curso I – TC581",
                "Trabalho Final de Curso I – TH581",
                "Trabalho Final de Curso I – TT581",
                "Projeto de Infraestrutura e Obras Especiais – TC595",
                "Projeto de Infraestrutura e Obras Especiais – TH595",
                "Projeto de Infraestrutura e Obras Especiais – TT595"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC582",
                "Trabalho Final de Curso II – TH582",
                "Trabalho Final de Curso II – TT582",
                "Trabalho Final de Curso II – TC583",
                "Trabalho Final de Curso II – TH583",
                "Trabalho Final de Curso II – TT583",
                "Estágio Supervisionado Obrigatório – TC585",
                "Estágio Supervisionado Obrigatório – TH585",
                "Estágio Supervisionado Obrigatório – TT585",
                "Projetos de Edifícios – TC596",
                "Projetos de Edifícios – TH596",
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        }
    },
    "Engenharia de Computação": {
        "Ementa - 2015": {
            "1º Semestre": [
                "Cálculo Diferencial e Integral I – CM201",
                "Eletricidade Aplicada – TE144",
                "Expressão Gráfica I – CD027",
                "Geometria Analítica – CM045",
                "Introdução à Engenharia – TC022",
                "Mecânica Geral I – TC021",
                "Programação de Computadores – CI208"
            ],
            "2º Semestre": [
                "Álgebra Linear – CM005",
                "Cálculo Diferencial e Integral II – CM202",
                "Construção Civil I – TC024",
                "Expressão Gráfica II – CD028",
                "Mecânica Geral II – TC023",
                "Métodos Numéricos – CI202"
            ],
            "3º Semestre": [
                "Cálculo III – CM043",
                "Construção Civil II – TC025",
                "Estatística II – CE003",
                "Mecânica dos Fluidos I – TH019",
                "Mecânica Geral III – TC027",
                "Resistência dos Materiais I – TC026",
                "Topografia I – GA069"
            ],
            "4º Semestre": [
                "Introdução à Engenharia Geotécnica – TC029",
                "Ciências do Ambiente – TH022",
                "Materiais de Construção Civil I – TC030",
                "Mecânica dos Fluidos II – TH021",
                "Resistência dos Materiais II – TC028",
                "Sistemas de Transporte – TT046",
                "Topografia II – GA070"
            ],
            "5º Semestre": [
                "Estruturação Sanitária das Cidades – TH025",
                "Hidráulica – TH020",
                "Infra-Estrutura Viária – TT048",
                "Laboratório de Mecânica dos Solos – TC033",
                "Materiais de Construção Civil II – TC031",
                "Mecânica das Estruturas I – TC032"
            ],
            "6º Semestre": [
                "Atividades Formativas – AAC005",
                "Equipamentos de Construção e Conservação – TT047",
                "Hidráulica e Hidrologia Experimental – TH027",
                "Hidrologia – TH024",
                "Materiais de Construção Civil III – TC034",
                "Mecânica das Estruturas II – TC036",
                "Mecânica dos Solos – TC035"
            ],
            "7º Semestre": [
                "Construção Civil III – TC038",
                "Engenharia de Recursos Hídricos – TH026",
                "Engenharia Social – TH045",
                "Estruturas de Concreto I – TC037",
                "Laboratório de Materiais de Construção – TC039",
                "Obras Geotécnicas – TC066",
                "Planejamento de Transportes – TT049",
                "Saneamento Ambiental I – TH028"
            ],
            "8º Semestre": [
                "Construção Civil IV – TC042",
                "Economia de Engenharia I – TT007",
                "Estágio Supervisionado – TC046",
                "Estágio Supervisionado – TH043",
                "Estágio Supervisionado – TT054",
                "Estruturas de Concreto II – TC040",
                "Geotecnia de Fundações – TC041",
                "Pavimentação – TT051",
                "Saneamento Ambiental II – TH029"
            ],
            "9º Semestre": [
                "Administração de Empresas de Engenharia I – TT008",
                "Estrutura de Edifícios I – TC044",
                "Estruturas Metálicas I – TC043",
                "Gerenciamento de Projetos – TC045",
                "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
                "Trabalho Final de Curso I – TC081",
                "Trabalho Final de Curso I – TH061",
                "Trabalho Final de Curso I – TT071"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC082",
                "Trabalho Final de Curso II – TH062",
                "Trabalho Final de Curso II – TT072"
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        },
        "Ementa - 2021": {
            "1º Semestre": [
                "Expressão Gráfica A – CEG019",
                "Fundamentação de Programação de Computadores – CI182",
                "Pré-Cálculo – CM310",
                "Física I – TC501",
                "Química Aplicada – TC502",
                "Introdução à Engenharia e Inovação – TC591",
                "Introdução à Engenharia e Inovação – TH591",
                "Introdução à Engenharia e Inovação – TT591"
            ],
            "2º Semestre": [
                "Métodos Numéricos – CI202",
                "Introdução à Geometria Analítica e Álgebra Linear – CM303",
                "Cálculo 1 – CM311",
                "Desenho Arquitetônico – TC503",
                "Análise Estrutural I – TC504",
                "Física II – TH512"
            ],
            "3º Semestre": [
                "Introdução à Estatística – CE009",
                "Cálculo 2 – CM312",
                "Topografia I – GA175",
                "Construção Civil I – TC505",
                "Análise Estrutural II – TC506",
                "Sistemas Estruturais – TC507",
                "Mecânica dos Fluídos I – TH501",
                "Sistemas de Transporte – TT501"
            ],
            "4º Semestre": [
                "Cálculo 4 – CM314",
                "Topografia II – GA176",
                "Construção Civil II – TC508",
                "Mecânica dos Sólidos I – TC509",
                "Materiais de Construção Civil I – TC510",
                "Laboratório de Materiais de Construção Civil – TC511",
                "Mecânica dos Fluídos II – TH502",
                "Mecânica dos Fluídos Experimental – TH503"
            ],
            "5º Semestre": [
                "Caracterização Geológica - Geotécnica – TC512",
                "Mecânica dos Sólidos II – TC513",
                "Materiais de Construção Civil II – TC514",
                "Hidráulica – TH504",
                "Ciências do Ambiente – TH508",
                "Planejamento e Operação de Transportes – TT502",
                "Engenharia Civil e Sustentabilidade – TC592",
                "Engenharia Civil e Sustentabilidade – TH592",
                "Engenharia Civil e Sustentabilidade – TT592",
            ],
            "6º Semestre": [
                "Hidráulica dos Solos – TC515",
                "Análise Estrutural III – TC516",
                "Construção Civil III – TC517",
                "Hidrologia – TH505",
                "Hidráulica e Hidrologia Experimental – TH506",
                "Equipamentos de Terraplanagem e de Pavimentação – TT503",
                "Estruturação das Cidades – TH593",
                "Estruturação das Cidades – TT593"
            ],
            "7º Semestre": [
                "Mecânica dos Solos – TC518",
                "Estruturas de Concreto I – TC519",
                "Gestão de Projetos – TC520",
                "Engenharia de Recursos Hídricos – TH507",
                "Saneamento Ambiental I – TH509",
                "Engenharia Econômica – TT504",
                "Engenharia Urbana – TH594",
                "Engenharia Urbana – TT594"
            ],
            "8º Semestre": [
                "Obras Geotécnicas – TC521",
                "Estruturas de Concreto II – TC522",
                "Saneamento Ambiental II – TH510",
                "Estradas – TT505",
                "Pavimentação – TT506",
                "Laboratório de Transportes – TT507",
                "Economia de Engenharia – TT508",
                "Metodologia do Trabalho Científico e Tecnológico – TT509"
            ],
            "9º Semestre": [
                "Estruturas de Aço – TC523",
                "Estruturas de Madeira – TC524",
                "Engenharia de Fundações – TC525",
                "Eletricidade Aplicada – TE144",
                "Engenharia e Sociedade – TH511",
                "Administração de Empresas – TT510",
                "Trabalho Final de Curso I – TC581",
                "Trabalho Final de Curso I – TH581",
                "Trabalho Final de Curso I – TT581",
                "Projeto de Infraestrutura e Obras Especiais – TC595",
                "Projeto de Infraestrutura e Obras Especiais – TH595",
                "Projeto de Infraestrutura e Obras Especiais – TT595"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC582",
                "Trabalho Final de Curso II – TH582",
                "Trabalho Final de Curso II – TT582",
                "Trabalho Final de Curso II – TC583",
                "Trabalho Final de Curso II – TH583",
                "Trabalho Final de Curso II – TT583",
                "Estágio Supervisionado Obrigatório – TC585",
                "Estágio Supervisionado Obrigatório – TH585",
                "Estágio Supervisionado Obrigatório – TT585",
                "Projetos de Edifícios – TC596",
                "Projetos de Edifícios – TH596",
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        }
    },
    "Engenharia Elétrica": {
        "Ementa - 2013": {
            "1º Semestre": [
                "Cálculo Diferencial e Integral I – CM201",
                "Eletricidade Aplicada – TE144",
                "Expressão Gráfica I – CD027",
                "Geometria Analítica – CM045",
                "Introdução à Engenharia – TC022",
                "Mecânica Geral I – TC021",
                "Programação de Computadores – CI208"
            ],
            "2º Semestre": [
                "Álgebra Linear – CM005",
                "Cálculo Diferencial e Integral II – CM202",
                "Construção Civil I – TC024",
                "Expressão Gráfica II – CD028",
                "Mecânica Geral II – TC023",
                "Métodos Numéricos – CI202"
            ],
            "3º Semestre": [
                "Cálculo III – CM043",
                "Construção Civil II – TC025",
                "Estatística II – CE003",
                "Mecânica dos Fluidos I – TH019",
                "Mecânica Geral III – TC027",
                "Resistência dos Materiais I – TC026",
                "Topografia I – GA069"
            ],
            "4º Semestre": [
                "Introdução à Engenharia Geotécnica – TC029",
                "Ciências do Ambiente – TH022",
                "Materiais de Construção Civil I – TC030",
                "Mecânica dos Fluidos II – TH021",
                "Resistência dos Materiais II – TC028",
                "Sistemas de Transporte – TT046",
                "Topografia II – GA070"
            ],
            "5º Semestre": [
                "Estruturação Sanitária das Cidades – TH025",
                "Hidráulica – TH020",
                "Infra-Estrutura Viária – TT048",
                "Laboratório de Mecânica dos Solos – TC033",
                "Materiais de Construção Civil II – TC031",
                "Mecânica das Estruturas I – TC032"
            ],
            "6º Semestre": [
                "Atividades Formativas – AAC005",
                "Equipamentos de Construção e Conservação – TT047",
                "Hidráulica e Hidrologia Experimental – TH027",
                "Hidrologia – TH024",
                "Materiais de Construção Civil III – TC034",
                "Mecânica das Estruturas II – TC036",
                "Mecânica dos Solos – TC035"
            ],
            "7º Semestre": [
                "Construção Civil III – TC038",
                "Engenharia de Recursos Hídricos – TH026",
                "Engenharia Social – TH045",
                "Estruturas de Concreto I – TC037",
                "Laboratório de Materiais de Construção – TC039",
                "Obras Geotécnicas – TC066",
                "Planejamento de Transportes – TT049",
                "Saneamento Ambiental I – TH028"
            ],
            "8º Semestre": [
                "Construção Civil IV – TC042",
                "Economia de Engenharia I – TT007",
                "Estágio Supervisionado – TC046",
                "Estágio Supervisionado – TH043",
                "Estágio Supervisionado – TT054",
                "Estruturas de Concreto II – TC040",
                "Geotecnia de Fundações – TC041",
                "Pavimentação – TT051",
                "Saneamento Ambiental II – TH029"
            ],
            "9º Semestre": [
                "Administração de Empresas de Engenharia I – TT008",
                "Estrutura de Edifícios I – TC044",
                "Estruturas Metálicas I – TC043",
                "Gerenciamento de Projetos – TC045",
                "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
                "Trabalho Final de Curso I – TC081",
                "Trabalho Final de Curso I – TH061",
                "Trabalho Final de Curso I – TT071"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC082",
                "Trabalho Final de Curso II – TH062",
                "Trabalho Final de Curso II – TT072"
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        },
        "Ementa - 2019": {
            "1º Semestre": [
                "Expressão Gráfica A – CEG019",
                "Fundamentação de Programação de Computadores – CI182",
                "Pré-Cálculo – CM310",
                "Física I – TC501",
                "Química Aplicada – TC502",
                "Introdução à Engenharia e Inovação – TC591",
                "Introdução à Engenharia e Inovação – TH591",
                "Introdução à Engenharia e Inovação – TT591"
            ],
            "2º Semestre": [
                "Métodos Numéricos – CI202",
                "Introdução à Geometria Analítica e Álgebra Linear – CM303",
                "Cálculo 1 – CM311",
                "Desenho Arquitetônico – TC503",
                "Análise Estrutural I – TC504",
                "Física II – TH512"
            ],
            "3º Semestre": [
                "Introdução à Estatística – CE009",
                "Cálculo 2 – CM312",
                "Topografia I – GA175",
                "Construção Civil I – TC505",
                "Análise Estrutural II – TC506",
                "Sistemas Estruturais – TC507",
                "Mecânica dos Fluídos I – TH501",
                "Sistemas de Transporte – TT501"
            ],
            "4º Semestre": [
                "Cálculo 4 – CM314",
                "Topografia II – GA176",
                "Construção Civil II – TC508",
                "Mecânica dos Sólidos I – TC509",
                "Materiais de Construção Civil I – TC510",
                "Laboratório de Materiais de Construção Civil – TC511",
                "Mecânica dos Fluídos II – TH502",
                "Mecânica dos Fluídos Experimental – TH503"
            ],
            "5º Semestre": [
                "Caracterização Geológica - Geotécnica – TC512",
                "Mecânica dos Sólidos II – TC513",
                "Materiais de Construção Civil II – TC514",
                "Hidráulica – TH504",
                "Ciências do Ambiente – TH508",
                "Planejamento e Operação de Transportes – TT502",
                "Engenharia Civil e Sustentabilidade – TC592",
                "Engenharia Civil e Sustentabilidade – TH592",
                "Engenharia Civil e Sustentabilidade – TT592",
            ],
            "6º Semestre": [
                "Hidráulica dos Solos – TC515",
                "Análise Estrutural III – TC516",
                "Construção Civil III – TC517",
                "Hidrologia – TH505",
                "Hidráulica e Hidrologia Experimental – TH506",
                "Equipamentos de Terraplanagem e de Pavimentação – TT503",
                "Estruturação das Cidades – TH593",
                "Estruturação das Cidades – TT593"
            ],
            "7º Semestre": [
                "Mecânica dos Solos – TC518",
                "Estruturas de Concreto I – TC519",
                "Gestão de Projetos – TC520",
                "Engenharia de Recursos Hídricos – TH507",
                "Saneamento Ambiental I – TH509",
                "Engenharia Econômica – TT504",
                "Engenharia Urbana – TH594",
                "Engenharia Urbana – TT594"
            ],
            "8º Semestre": [
                "Obras Geotécnicas – TC521",
                "Estruturas de Concreto II – TC522",
                "Saneamento Ambiental II – TH510",
                "Estradas – TT505",
                "Pavimentação – TT506",
                "Laboratório de Transportes – TT507",
                "Economia de Engenharia – TT508",
                "Metodologia do Trabalho Científico e Tecnológico – TT509"
            ],
            "9º Semestre": [
                "Estruturas de Aço – TC523",
                "Estruturas de Madeira – TC524",
                "Engenharia de Fundações – TC525",
                "Eletricidade Aplicada – TE144",
                "Engenharia e Sociedade – TH511",
                "Administração de Empresas – TT510",
                "Trabalho Final de Curso I – TC581",
                "Trabalho Final de Curso I – TH581",
                "Trabalho Final de Curso I – TT581",
                "Projeto de Infraestrutura e Obras Especiais – TC595",
                "Projeto de Infraestrutura e Obras Especiais – TH595",
                "Projeto de Infraestrutura e Obras Especiais – TT595"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC582",
                "Trabalho Final de Curso II – TH582",
                "Trabalho Final de Curso II – TT582",
                "Trabalho Final de Curso II – TC583",
                "Trabalho Final de Curso II – TH583",
                "Trabalho Final de Curso II – TT583",
                "Estágio Supervisionado Obrigatório – TC585",
                "Estágio Supervisionado Obrigatório – TH585",
                "Estágio Supervisionado Obrigatório – TT585",
                "Projetos de Edifícios – TC596",
                "Projetos de Edifícios – TH596",
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        }
    },
    "Técnico em Edificações": {
        "Ementa - 2014": {
            "1º Semestre": [
                "Fundamentos Físicos e Matemáticos para Edificações – EDF1001",
                "Informática Instrumental – EDF1002",
                "Desenho Técnico – EDF1003",
                "Desenho Digital Básico – EDF1004",
                "Técnicas Básicas de Construção Civil – EDF1005",
                "Materiais de Construção Civil – EDF1006",
                "Higiene e Segurança do Trabalho – EDF1007"
            ],
            "2º Semestre": [
                "Desenho Arquitetônico – EDF1008",
                "Desenho Digital Avançado – EDF1009",
                "Resistência dos Materiais – EDF1010",
                "Tecnologia do Concreto – EDF1011",
                "Práticas Básicas de Construção Civil – EDF1012",
                "Técnicas Complementares de Construção Civil – EDF1013"
            ],
            "3º Semestre": [
                "Mecânica dos Solos e Fundações – EDF1014",
                "Topografia – EDF1015",
                "Sistemas Estruturais – EDF1016",
                "Teoria das Instalações Elétricas Prediais – EDF1017",
                "Teoria das Instalações Hidráulicas Prediais – EDF1018",
                "Projeto Arquitetônico – EDF1019"
            ],
            "4º Semestre": [
                "Práticas Complementares e Instalações Prediais – EDF1020",
                "Impactos Ambientais – EDF1021",
                "Gestão de Obras – EDF1022",
                "Orçamento de Obras – EDF1023",
                "Planejamento de Obras – EDF1024",
                "Projeto Integrado – EDF1025"
            ]
        }
    }
}

lista_cursos = ["", "Engenharia Civil", "Engenharia de Computação", "Engenharia Elétrica", "Técnico em Edificações"]

lista_turmas = ["", "Turma A", "Turma B", "Turma C", "Turma D", "Turma E", "Turma F", "Turma G",
                "Turma H", "Turma I", "Turma J", "Turma K", "Turma L", "Turma M", "Turma N",
                "Turma O", "Turma P", "Turma Q", "Turma R", "Turma S", "Turma T", "Turma U",
                "Turma V", "Turma W", "Turma X", "Turma Y", "Turma Z"]

lista_avaliacoes = ["", "PROVA", "TESTE", "2ª CHAMADA", "EXAME FINAL", "TRABALHO", "RELATÓRIO", "LISTA DE EXERCÍCIOS",
                    "EXERCÍCIO", "APRESENTAÇÃO ORAL", "SEMINÁRIO", "KAHOOT", "ROCKBOWL",
                    "APRENDIZADO BASEADO EM PROBLEMAS (PBL)",
                    "APRENDIZADO BASEADO EM PROJETOS (ABP)",
                    "APRENDIZADO BASEADO EM INQUÉRITO (IBL)"]

dicionario_disciplinas = {
    "1ª Coloracao Disciplina": [
        "",
        "Cálculo Diferencial e Integral I – CM201",
        "Mecânica Geral II – TC023",
        "Materiais de Construção Civil I – TC030",
        "Atividades Formativas – AAC005",
        "Laboratório de Materiais de Construção – TC039",
        "Pavimentação – TT051",
        "Trabalho Final de Curso II – TH062",
        "Ferrovias – TT066",
        "Fundamentos Físicos e Matemáticos para Edificações – EDF1001",
        "Projeto Integrado – EDF1025"
    ],
    "2ª Coloracao Disciplina": [
        "",
        "Eletricidade Aplicada – TE144",
        "Métodos Numéricos – CI202",
        "Mecânica dos Fluidos II – TH021",
        "Equipamentos de Construção e Conservação – TT047",
        "Obras Geotécnicas – TC066",
        "Saneamento Ambiental II – TH029",
        "Trabalho Final de Curso II – TT072",
        "Geologia de Engenharia – TC049",
        "Legislação e Prática Profissional – TC061",
        "Informática Instrumental – EDF1002"
    ],
    "3ª Coloracao Disciplina": [
        "",
        "Expressão Gráfica I – CD027",
        "Cálculo III – CM043",
        "Resistência dos Materiais II – TC028",
        "Hidráulica e Hidrologia Experimental – TH027",
        "Planejamento de Transportes – TT049",
        "Administração de Empresas de Engenharia I – TT008",
        "Avaliação de Impactos Ambientais – TT059",
        "Geotecnia Ambiental – TC053",
        "Logística e Transporte – TT058",
        "Desenho Técnico – EDF1003"
    ],
    "4ª Coloracao Disciplina": [
        "",
        "Geometria Analítica – CM045",
        "Construção Civil II – TC025",
        "Sistemas de Transporte – TT046",
        "Hidrologia – TH024",
        "Saneamento Ambiental I – TH028",
        "Estrutura de Edifícios I – TC044",
        "Engenharia de Avaliações – TC064",
        "Geotecnia Aplicada as Vias de Transporte – TT065",
        "Mecânica das Rochas – TC051",
        "Desenho Digital Básico – EDF1004"
    ],
    "5ª Coloracao Disciplina": [
        "",
        "Introdução à Engenharia – TC022",
        "Estatística II – CE003",
        "Topografia II – GA070",
        "Materiais de Construção Civil III – TC034",
        "Construção Civil IV – TC042",
        "Estruturas Metálicas I – TC043",
        "Engenharia de Tráfego – TT056",
        "Geotecnia de Taludes e Contenções – TC052",
        "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
        "Técnicas Básicas de Construção Civil – EDF1005"
    ],
    "6ª Coloracao Disciplina": [
        "",
        "Mecânica Geral I – TC021",
        "Mecânica dos Fluidos I – TH019",
        "Estruturação Sanitária das Cidades – TH025",
        "Mecânica das Estruturas II – TC036",
        "Economia de Engenharia I – TT007",
        "Gerenciamento de Projetos – TC045",
        "Engenharia Econômica de Recursos Hídricos – TH035",
        "Gerenciamento de Empreendimentos – TC062",
        "Modelagem e Planejamento de Transportes Urbanos – TT060",
        "Materiais de Construção Civil – EDF1006"
    ],
    "7ª Coloracao Disciplina": [
        "",
        "Programação de Computadores – CI208",
        "Mecânica Geral III – TC027",
        "Hidráulica – TH020",
        "Mecânica dos Solos – TC035",
        "Estágio Supervisionado – TC046",
        "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
        "Estruturas de Concreto III – TC054",
        "Gerenciamento de Recursos Hídricos – TH036",
        "Higiene e Segurança do Trabalho – EDF1007"
    ],
    "8ª Coloracao Disciplina": [
        "",
        "Álgebra Linear – CM005",
        "Resistência dos Materiais I – TC026",
        "Infra-Estrutura Viária – TT048",
        "Construção Civil III – TC038",
        "Estágio Supervisionado – TH043",
        "Trabalho Final de Curso I – TC081",
        "Estruturas de Edifícios II – TC056",
        "Gerenciamento de Rodovias e Vias Urbanas – TT063",
        "Desenho Arquitetônico – EDF1008"
    ],
    "9ª Coloracao Disciplina": [
        "",
        "Cálculo Diferencial e Integral II – CM202",
        "Topografia I – GA069",
        "Laboratório de Mecânica dos Solos – TC033",
        "Engenharia de Recursos Hídricos – TH026",
        "Estágio Supervisionado – TT054",
        "Trabalho Final de Curso I – TH061",
        "Estruturas de Madeira – TC057",
        "Hidráulica Ambiental – TH033",
        "Desenho Digital Avançado – EDF1009"
    ],
    "10ª Coloracao Disciplina": [
        "",
        "Construção Civil I – TC024",
        "Introdução à Engenharia Geotécnica – TC029",
        "Materiais de Construção Civil II – TC031",
        "Engenharia Social – TH045",
        "Estruturas de Concreto II – TC040",
        "Trabalho Final de Curso I – TT071",
        "Estruturas Metálicas II – TC055",
        "Hidráulica Fluvial – TH032",
        "Resistência dos Materiais – EDF1010"
    ],
    "11ª Coloracao Disciplina": [
        "",
        "Expressão Gráfica II – CD028",
        "Ciências do Ambiente – TH022",
        "Mecânica das Estruturas I – TC032",
        "Estruturas de Concreto I – TC037",
        "Geotecnia de Fundações – TC041",
        "Trabalho Final de Curso II – TC082",
        "Expressão Gráfica III – CD035",
        "Instalações Prediais Especiais – TC065",
        "Tecnologia do Concreto – EDF1011"
    ],
    "12ª Coloracao Disciplina": [
        "",
        "Introdução a Engenharia de Segurança do Trabalho – TT068",
        "Projetos de Drenagem Urbana – TH037",
        "Tópicos Avançados em Geotecnia – TC048",
        "Introdução à Geometria Analítica e Álgebra Linear – CM303",
        "Mecânica dos Fluídos I – TH501",
        "Mecânica dos Sólidos II – TC513",
        "Hidrologia – TH505",
        "Engenharia Urbana – TH594",
        "Estruturas de Madeira – TC524",
        "Práticas Básicas de Construção Civil – EDF1012"
    ],
    "13ª Coloracao Disciplina": [
        "",
        "Projetos de Obras Hidráulicas – TH031",
        "Transporte Público – TT057",
        "Cálculo 1 – CM311",
        "Sistemas de Transporte – TT501",
        "Materiais de Construção Civil II – TC514",
        "Hidráulica e Hidrologia Experimental – TH506",
        "Engenharia Urbana – TT594",
        "Engenharia de Fundações – TC525",
        "Técnicas Complementares de Construção Civil – EDF1013"
    ],
    "14ª Coloracao Disciplina": [
        "",
        "Projetos de Obras Viárias – TT064",
        "Expressão Gráfica A – CEG019",
        "Desenho Arquitetônico – TC503",
        "Cálculo 4 – CM314",
        "Hidráulica – TH504",
        "Equipamentos de Terraplanagem e de Pavimentação – TT503",
        "Obras Geotécnicas – TC521",
        "Eletricidade Aplicada – TE144",
        "Mecânica dos Solos e Fundações – EDF1014"
    ],
    "15ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
        "Fundamentação de Programação de Computadores – CI182",
        "Análise Estrutural I – TC504",
        "Topografia II – GA176",
        "Ciências do Ambiente – TH508",
        "Estruturação das Cidades – TH593",
        "Estruturas de Concreto II – TC522",
        "Engenharia e Sociedade – TH511",
        "Topografia – EDF1015"
    ],
    "16ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas de Saneamento Ambiental – TH039",
        "Pré-Cálculo – CM310",
        "Física II – TH512",
        "Construção Civil II – TC508",
        "Planejamento e Operação de Transportes – TT502",
        "Estruturação das Cidades – TT593",
        "Saneamento Ambiental II – TH510",
        "Administração de Empresas – TT510",
        "Sistemas Estruturais – EDF1016"
    ],
    "17ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
        "Física I – TC501",
        "Introdução à Estatística – CE009",
        "Mecânica dos Sólidos I – TC509",
        "Engenharia Civil e Sustentabilidade – TC592",
        "Mecânica dos Solos – TC518",
        "Estradas – TT505",
        "Trabalho Final de Curso I – TC581",
        "Teoria das Instalações Elétricas Prediais – EDF1017"
    ],
    "18ª Coloracao Disciplina": [
        "",
        "Qualidade e Conservação Ambiental – TH041",
        "Química Aplicada – TC502",
        "Cálculo 2 – CM312",
        "Materiais de Construção Civil I – TC510",
        "Engenharia Civil e Sustentabilidade – TH592",
        "Estruturas de Concreto I – TC519",
        "Pavimentação – TT506",
        "Trabalho Final de Curso I – TH581",
        "Teoria das Instalações Hidráulicas Prediais – EDF1018"
    ],
    "19ª Coloracao Disciplina": [
        "",
        "Segurança Viária – TT061",
        "Introdução à Engenharia e Inovação – TC591",
        "Topografia I – GA175",
        "Laboratório de Materiais de Construção Civil – TC511",
        "Engenharia Civil e Sustentabilidade – TT592",
        "Gestão de Projetos – TC520",
        "Laboratório de Transportes – TT507",
        "Trabalho Final de Curso I – TT581",
        "Projeto Arquitetônico – EDF1019"
    ],
    "20ª Coloracao Disciplina": [
        "",
        "Sistemas de Recursos Hídricos – TH034",
        "Introdução à Engenharia e Inovação – TH591",
        "Construção Civil I – TC505",
        "Mecânica dos Fluídos II – TH502",
        "Hidráulica dos Solos – TC515",
        "Engenharia de Recursos Hídricos – TH507",
        "Economia de Engenharia – TT508",
        "Projeto de Infraestrutura e Obras Especiais – TC595",
        "Práticas Complementares e Instalações Prediais – EDF1020"
    ],
    "21ª Coloracao Disciplina": [
        "",
        "Técnica de Investigação Geotécnica e Instrumentação – TC050",
        "Introdução à Engenharia e Inovação – TT591",
        "Análise Estrutural II – TC506",
        "Mecânica dos Fluídos Experimental – TH503",
        "Análise Estrutural III – TC516",
        "Saneamento Ambiental I – TH509",
        "Metodologia do Trabalho Científico e Tecnológico – TT509",
        "Projeto de Infraestrutura e Obras Especiais – TH595",
        "Impactos Ambientais – EDF1021"
    ],
    "22ª Coloracao Disciplina": [
        "",
        "Tópicos Avançados de Pavimentação – TT062",
        "Métodos Numéricos – CI202",
        "Sistemas Estruturais – TC507",
        "Caracterização Geológica - Geotécnica – TC512",
        "Construção Civil III – TC517",
        "Engenharia Econômica – TT504",
        "Estruturas de Aço – TC523",
        "Projeto de Infraestrutura e Obras Especiais – TT595",
        "Gestão de Obras – EDF1022"
    ],
    "23ª Coloracao Disciplina": [
        "",
        "Trabalho Final de Curso II – TC583",
        "Trabalho Final de Curso II – TH583",
        "Trabalho Final de Curso II – TT583",
        "Estágio Supervisionado Obrigatório – TC585",
        "Estágio Supervisionado Obrigatório – TH585",
        "Estágio Supervisionado Obrigatório – TT585",
        "Projetos de Edifícios – TC596",
        "Projetos de Edifícios – TH596",
        "Orçamento de Obras – EDF1023"
    ],
    "24ª Coloracao Disciplina": [
        "",
        "Planejamento e Gestão dos Sistemas Urbanos – TH042",
        "Pontes e Estruturas Especiais – TC058",
        "Portos e Hidrovias – TT067",
        "Projeto de Obras Viárias – TT064",
        "Projetos de Arquitetura – TC060",
        "Trabalho Final de Curso II – TC582",
        "Trabalho Final de Curso II – TH582",
        "Trabalho Final de Curso II – TT582",
        "Planejamento de Obras – EDF1024"
    ]
}

dicionario_de_cores = {
    "1ª Coloracao Disciplina": "#FF0000",  # red
    "2ª Coloracao Disciplina": "#0000FF",  # blue
    "3ª Coloracao Disciplina": "#008000",  # green
    "4ª Coloracao Disciplina": "#808000",  # olive
    "5ª Coloracao Disciplina": "#800080",  # purple
    "6ª Coloracao Disciplina": "#FFA500",  # orange
    "7ª Coloracao Disciplina": "#A52A2A",  # brown
    "8ª Coloracao Disciplina": "#FF1493",  # deeppink
    "9ª Coloracao Disciplina": "#008080",  # teal
    "10ª Coloracao Disciplina": "#FF00FF",  # magenta
    "11ª Coloracao Disciplina": "#2F4F4F",  # darkslategray
    "12ª Coloracao Disciplina": "#00FFFF",  # cyan
    "13ª Coloracao Disciplina": "#FFD700",  # gold
    "14ª Coloracao Disciplina": "#4B0082",  # indigo
    "15ª Coloracao Disciplina": "#00FF00",  # lime
    "16ª Coloracao Disciplina": "#FF4500",  # orangered
    "17ª Coloracao Disciplina": "#DA70D6",  # orchid
    "18ª Coloracao Disciplina": "#87CEEB",  # skyblue
    "19ª Coloracao Disciplina": "#4682B4",  # steelblue
    "20ª Coloracao Disciplina": "#D2691E",  # chocolate
    "21ª Coloracao Disciplina": "#B22222",  # firebrick
    "22ª Coloracao Disciplina": "#FF6347",  # tomato
    "23ª Coloracao Disciplina": "#40E0D0",  # turquoise
    "24ª Coloracao Disciplina": "#9ACD32"   # yellowgreen
}
